app = "e-compare-backend"
primary_region = "sin" # Replace with your preferred Fly.io region (e.g., "iad" for Ashburn, Virginia)

# Build configuration
[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]
  [build.args]
    PYTHON_VERSION = "3.9.0"

# Environment variables
[env]
  ALLOWED_ORIGINS = "https://e-compare-frontend.onrender.com"

# HTTP service configuration
[http_service]
  internal_port = 8000 # Default port for Uvicorn; Fly.io maps this to external 443/80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# Processes (maps to startCommand)
[processes]
  app = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

# Mounts (optional, if you need persistent storage)
# [[mounts]]
#   source = "data"
#   destination = "/data"

# Optional: Define secrets (OPENAI_API_KEY)
# Secrets are set separately via `fly secrets set OPENAI_API_KEY=<value>`