# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - e-compare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Matches pythonVersion: 3.9.0 in render.yaml

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt # Matches buildCommand in render.yaml

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Create startup file for Azure Web App
        run: |
          echo "cd backend && uvicorn main:app --host 0.0.0.0 --port \$PORT" > startup.txt # Matches startCommand in render.yaml

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r -x "venv/*" # Exclude virtual environment

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_350636F14C45497F94B4A62DDDB84456 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36D7441CBF294B63B9902E3E7881652A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_075CB38668CB4076A4019852CA0AAC83 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'e-compare'
          slot-name: 'Production'
          # Set environment variables for Azure Web App
          application-settings-json: |
            {
              "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}",
              "ALLOWED_ORIGINS": "https://e-compare.vercel.app/"
              "DB_HOST": "e-compare-sql-server-e-compare.j.aivencloud.com",
              "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
              "JWT_SECRET_KEY": "${{ secrets.JWT_SECRET_KEY }}",
            }